services:
  - type: web
    name: chk-no-face-clan-api
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://nofacechk.com
      - key: ADMIN_PASS
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_SETUP_KEY
        sync: false

  - type: static_site
    name: chk-no-face-clan
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        value: pk_test_51TmP0G6cfmpKwb4mXrdUmWd5mpyCnwommPNQrL0xiMiNo51tIuwv8mO5NN8TTNkKNg8mjI5gZvaUm8puI2JmXCtI003KKfe6U6
      - key: VITE_PAYMENTS_API
        value: https://chk-no-face-clan-api.onrender.com
